const addMovesGen9 = {
  'Silk Trap': '스레드트랩',
  'Axe Kick': '발꿈치찍기',
  'Last Respects': '성묘',
  'Lumina Crash': '루미나콜리전',
  'Order Up': '한판내기',
  'Jet Punch': '제트펀치',
  'Spicy Extract': '하바네로엑기스',
  'Spin Out': '휠스핀',
  'Population Bomb': '찍찍베기',
  'Ice Spinner': '아이스스피너',
  'Glaive Rush': '대검돌격',
  'Revival Blessing': '회생의기도',
  'Salt Cure': '소금절이',
  'Triple Dive': '트리플다이브',
  'Mortal Spin': '킬러스핀',
  Doodle: '베껴그리기',
  'Fillet Away': '제살깎기',
  'Kowtow Cleave': '도각참',
  'Flower Trick': '트릭플라워',
  'Torch Song': '플레어송',
  'Aqua Step': '아쿠아스텝',
  'Raging Bull': '레이징불',
  'Make It Rain': '골드러시',
  Ruination: '카타스트로피',
  'Collision Course': '액셀브레이크',
  'Electro Drift': '라이트닝드라이브',
  'Shed Tail': '꼬리자르기',
  'Chilly Reception': '썰렁개그',
  'Tidy Up': '정리정돈',
  Snowscape: '설경',
  Pounce: '달려들기',
  Trailblaze: '개척하기',
  'Chilling Water': '찬물끼얹기',
  'Hyper Drill': '하이퍼드릴',
  'Twin Beam': '트윈빔',
  'Rage Fist': '분노의주먹',
  'Armor Cannon': '아머캐논',
  'Bitter Blade': '원념의칼',
  'Double Shock': '전광쌍격',
  'Gigaton Hammer': '거대해머',
  Comeuppance: '앙갚음',
  'Aqua Cutter': '아쿠아커터',
  'Tera Blast': '테라버스트',

  'Wave Crash': '웨이브태클',
  'Headlong Rush': '들이받기',
};

export { addMovesGen9 };
