import { Inter } from 'next/font/google';
import './styles/globals.css';
import './styles/type.css';
import React, { Suspense } from 'react';
import ClientProvider from './client-provider';
import { LanguageProvider } from './language-provider';
import Header from './ui/header';
import PokeCardSkelton from './ui/pokeCard/card-skeleton';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Poke mumu',
  description: 'Generated by create next app',
};

function CardListSkelton() {
  return (
    <div
      className="w-full grid grid-cols-1 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 2xl:grid-cols-7 sm:gap-x-4 gap-y-3 sm:gap-y-4 justify-center items-center"
    >
      {Array.from({ length: 240 }, (_, index) => (
        <PokeCardSkelton key={`card-${index}`} />
      ))}
    </div>
  );
}

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ClientProvider>
          <LanguageProvider>
            <Header />
            <div>
              {modal}
            </div>
            <main className="px-2.5 xs:px-4 sm:px-8 md:px-10 py-10 min-h-svh">
              <Suspense fallback={<CardListSkelton />}>
                {children}
              </Suspense>

            </main>
            <div id="modal" />
            <footer className="h-32" />
          </LanguageProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
