import { Inter, Noto_Sans_KR } from 'next/font/google';
import './styles/globals.css';
import './styles/type.css';
import React from 'react';
import ClienClientProvidertPor from './client-provider';

const inter = Inter({ subsets: ['latin'] });
// const notoSansKr = Noto_Sans_KR({ subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <header>Poke MuMu</header>
        <ClienClientProvidertPor>
          {children}
        </ClienClientProvidertPor>
      </body>
    </html>
  );
}
