import { Inter } from 'next/font/google';
import './styles/globals.css';
import './styles/type.css';
import React from 'react';
import ClientProvider from './client-provider';
import { LanguageProvider } from './language-provider';
import Header from './ui/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Poke mumu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ClientProvider>
          <LanguageProvider>
            <Header />
            <div>
              {modal}
            </div>
            <main className="px-2.5 xs:px-4 sm:px-8 md:px-10 py-6 min-h-svh">
              {children}
            </main>
            <div id="modal" />
            <footer className="h-32" />
          </LanguageProvider>
        </ClientProvider>
      </body>
    </html>
  );
}
